server:
    build: server
    volumes:
        - ./data:/data/teamcity
    ports:
        - "127.0.0.1:8111:8111"
    external_links:
        - mysql

agent:
    build: agent
    links:
        - server
    environment:
        - DEV_UID=103
        - DEV_GID=65534
    volumes:
        - /home/jackfengji/android-sdk-linux:/opt/android-sdk
        - ./agent/AgentSrc:/opt/teamcity-agent
